{"Launchpad":"https://bugs.launchpad.net/bugs/1402728","Id":"1402728","Gerrit":"https://review.openstack.org/141829","IdGerrit":"141829","IdCommit":"1b2aa11758fd52acdec0289777d276303555903b","Files":["nova/tests/unit/virt/vmwareapi/test_vm_util.py","nova/tests/unit/virt/vmwareapi/test_vmops.py","nova/virt/vmwareapi/vm_util.py","nova/virt/vmwareapi/vmops.py"],"Lines_Inseted":40,"Lines_Deleted":18,"CommitParent":"79dcd413808e2eeef8fe1432dd470069cc32ebf2","Classification":"Bug","KeywordsTitle":"resize, doesn't update, limits","Description":"does not update, limits, correctly","KeywordsCommit":"ensure,correctly, limits, may use, requires, updating","Comments":"it's a bug report, they described a fail resizing the VM."}