{"Launchpad":"https://bugs.launchpad.net/bugs/1419002","Id":"1419002","Gerrit":"https://review.openstack.org/153906","IdGerrit":"153906","IdCommit":"b838ca28e0ffda21b298a4514a647fc74c154f4a","Files":["nova/compute/utils.py","nova/tests/unit/virt/libvirt/test_driver.py","nova/virt/libvirt/driver.py"],"Lines_Inseted":31,"Lines_Deleted":0,"CommitParent":"6c90c96d7ce3f12252e8db97587af8924192c969","Classification":"Bug","KeywordsTitle":"  NOT, compain if 'my_ip' is wrong","Description":"my_ip config do not exit, failing, saliently accepts, error , warning ","KeywordsCommit":"log warning if my_ip not found, explicitly check,alert operators.","Comments":"Malfunctioning error"}