{"Launchpad":"https://bugs.launchpad.net/bugs/1431571","Id":"1431571","Gerrit":"https://review.openstack.org/164263","IdGerrit":"164263","IdCommit":"fa2a6afe7639726fad201a51832b8fcb06c95a75","Files":["nova/db/sqlalchemy/api.py","nova/tests/unit/db/test_db_api.py"],"Lines_Inseted":16,"Lines_Deleted":10,"CommitParent":"2c1784f150026c7b903fc920d480898ff51c424d","Classification":"Bug","KeywordsTitle":"relies on reflection to access the \"default\"","Description":"simple error in several of the tests, ","KeywordsCommit":"Fixed archiving of deleted records,  added specific column order for insert clause","Comments":"null"}