{"Launchpad":"https://bugs.launchpad.net/bugs/1438331","Id":"1438331","Gerrit":"https://review.openstack.org/203052","IdGerrit":"203052","IdCommit":"692b5ef984365a52cf4666050e57e3d17d528e79","Files":["nova/tests/virt/libvirt/test_rbd.py","nova/virt/libvirt/rbd_utils.py"],"Lines_Inseted":25,"Lines_Deleted":6,"CommitParent":"53c87f9c1bd776398877c6b042253213326f3184","Classification":"Bug","KeywordsTitle":"fails to delete, ERROR state","Description":"removing, will occasionally, ERROR state, fault,  reported, log","KeywordsCommit":"Fixes _cleanup, exception,this patch captures,remove.","Comments":"It's a bug report, (the good review is in https://review.openstack.org/#/c/169446/, this review was merged into master branch), We can see the logs and the error reported in the description so it's a bug"}