{
  "Launchpad": "https://bugs.launchpad.net/bugs/1475356",
  "Id": "1475356",
  "Gerrit": "https://review.openstack.org/205683",
  "IdGerrit": "205683",
  "IdCommit": "7c0e2238eb003ac0c620f4b63fa92baa6675e724",
  "Files": [
    "nova/objects/base.py",
    "nova/tests/unit/objects/test_objects.py"
  ],
  "Lines_Inseted": 8,
  "Lines_Deleted": 3,
  "CommitParent": "b2a04bcfe064994fb520fd63588f340d3ee0b942",
  "Classification": "Bug",
  "KeywordsTitle": "reports wrong",
  "Description": "",
  "KeywordsCommit": "Fix serializer supported version reporting, This patch fixes, causes the fault",
  "Comments": ""
}