{"Launchpad":"https://bugs.launchpad.net/bugs/1367032","Id":"1367032","Gerrit":"https://review.openstack.org/119953","IdGerrit":"119953","IdCommit":"0dc5d9f77e0d14f57ead1f53b9e2ad0a68faf786","Files":["neutron/plugins/vmware/dbexts/db.py","neutron/plugins/vmware/plugins/base.py","neutron/tests/unit/vmware/extensions/test_providernet.py"],"Lines_Inseted":6,"Lines_Deleted":0,"CommitParent":"8cd633ad19722c5e215c66e426282108826c9a6b","Classification":"Bug","KeywordsTitle":"unabled to delete","Description":"error, exception, cannot delete or update","KeywordsCommit":"allows us to provide a fix","Comments":""}
