{"Launchpad":"https://bugs.launchpad.net/bugs/1382076","Id":"1382076","Gerrit":"https://review.openstack.org/133411","IdGerrit":"133411","IdCommit":"6efe68b58fae2c08543b9f8e13fe7e1acd33a01e","Files":["neutron/common/ipv6_utils.py","neutron/db/db_base_plugin_v2.py","neutron/db/l3_db.py","neutron/tests/unit/plumgrid/test_plumgrid_plugin.py","neutron/tests/unit/test_db_plugin.py"],"Lines_Inseted":34,"Lines_Deleted":19,"CommitParent":"79353666b967c46722d75316fcc71bda5e567d32","Classification":"Bug","KeywordsTitle":"can not add,","Description":"after resolviing, imposible now, step to reproduce, it should be, to add","KeywordsCommit":"allow to add, patch will allow, ","Comments":"It's a bug report"}