{"Launchpad":"https://bugs.launchpad.net/bugs/1505166","Id":"1505166","Gerrit":"https://review.openstack.org/232661","IdGerrit":"232661","IdCommit":"3b6bd917e4b968a47a5aacb7f590143fc83816d9","Files":["neutron/agent/dhcp/agent.py","neutron/agent/l3/agent.py","neutron/common/constants.py","neutron/db/agents_db.py","neutron/plugins/ml2/drivers/linuxbridge/agent/linuxbridge_neutron_agent.py","neutron/plugins/ml2/drivers/openvswitch/agent/ovs_neutron_agent.py","neutron/tests/unit/agent/dhcp/test_agent.py","neutron/tests/unit/agent/l3/test_agent.py","neutron/tests/unit/plugins/ml2/drivers/linuxbridge/agent/test_linuxbridge_neutron_agent.py","neutron/tests/unit/plugins/ml2/drivers/openvswitch/agent/test_ovs_neutron_agent.py"],"Lines_Inseted":63,"Lines_Deleted":18,"CommitParent":"0312b1237b1a74aec82163ef863624d2607563d2","Classification":"Not_Bug","KeywordsTitle":"upon revival,","Description":"there could be, replicating,can't communicate, will rechedule,  cleanup, failed, conflicting, deleted","KeywordsCommit":"there could be, can't communicate, dead moving,  needs to cleanup, solution is, done by changing, would receive, should refresh.","Comments":"It's a new feature, in the description they said that there could be .... they didn't describe any failure in the system."}